<?php
    use App\Enums\ContactActionEnum;
    use App\Models\Contact;

    global $contacts;
?><!DOCTYPE html>
<html lang="de">
<head>
    <title>Liste von Kontakten</title>

    <link href="assets/styles/main.css" rel="stylesheet">
    <link href="node_modules/@fortawesome/fontawesome-free/css/all.min.css" rel="stylesheet">
    <script src="assets/scripts/main.js"></script>
</head>
<body>

    <header>
        <h1>Kontakte</h1>

        <nav>
            <a href="index.php">Home</a>
        </nav>
    </header>

    <main>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>E-Mail-Adresse</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($contacts as $contact): ?>
                    <?php /** @var Contact $contact */ ?>
                    <tr>
                        <td><?php echo htmlspecialchars($contact->getName()); ?></td>
                        <td><?php echo htmlspecialchars($contact->getEmail()); ?></td>
                        <td class="actions">
                            <a href="index.php?action=<?php echo ContactActionEnum::Edit->value; ?>&id=<?php echo $contact->getId(); ?>"
                               class="btn btn-primary"
                            ><i class="fas fa-edit"></i> Bearbeiten</a>
                            <a href="index.php?action=<?php echo ContactActionEnum::Delete->value; ?>&id=<?php echo $contact->getId(); ?>"
                               class="btn btn-danger btn-confirm"
                               data-message="Möchten Sie diesen Kontakt wirklich löschen?"
                            ><i class="fas fa-trash"></i> Löschen</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <div class="actions">
            <a href="index.php?action=<?php echo ContactActionEnum::Create->value; ?>"
               class="btn btn-primary"
            ><i class="fas fa-plus"></i> Neuen Kontakt erstellen</a>
        </div>
    </main>

    <footer>
        <p>&copy; <?php echo date('Y'); ?> Timo Paul Dienstleistungen</p>
    </footer>

</body>
</html>