<?php
use App\Enums\ContactActionEnum;
use App\Models\Contact;
?><table>
    <thead>
        <tr>
            <th>Name</th>
            <th>E-Mail-Adresse</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($contacts as $contact): ?>
            <?php /** @var Contact $contact */ ?>
            <tr>
                <td><?php echo htmlspecialchars($contact->getName()); ?></td>
                <td><?php echo htmlspecialchars($contact->getEmail()); ?></td>
                <td class="actions">
                    <a href="index.php?action=<?php echo ContactActionEnum::Edit->value; ?>&id=<?php echo $contact->getId(); ?>"
                       class="btn btn-primary"
                    ><i class="fas fa-edit"></i> Bearbeiten</a>
                    <a href="index.php?action=<?php echo ContactActionEnum::Delete->value; ?>&id=<?php echo $contact->getId(); ?>"
                       class="btn btn-danger btn-confirm"
                       data-message="Möchten Sie diesen Kontakt wirklich löschen?"
                    ><i class="fas fa-trash"></i> Löschen</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<div class="actions">
    <a href="index.php?action=<?php echo ContactActionEnum::Create->value; ?>"
       class="btn btn-primary"
    ><i class="fas fa-plus"></i> Neuen Kontakt erstellen</a>
</div>
