<!DOCTYPE html>
<html lang="de">
<head>
    <title><?php echo $title; ?></title>

    <link href="assets/styles/main.css" rel="stylesheet">
    <link href="node_modules/@fortawesome/fontawesome-free/css/all.min.css" rel="stylesheet">
    <script src="assets/scripts/main.js"></script>
</head>
<body>

<header>
    <h1><?php echo $title; ?></h1>

    <nav>
        <a href="index.php">Home</a>
    </nav>
</header>

<main>
    <?php if ( ! empty($flash)): ?>
        <div class="flash flash-<?php echo $flash['type']; ?> ">
            <?php echo htmlspecialchars($flash['message']); ?>
        </div>
    <?php endif; ?>

    <?php echo $content ?? ''; ?>
</main>

<footer>
    <p>&copy; <?php echo date('Y'); ?> Timo Paul Dienstleistungen</p>
</footer>

</body>
</html>